---
apiVersion: skaffold/v2beta24
kind: Config
metadata:
  name: app
build:
  local:
    useBuildkit: true
  artifacts:
    - image: ghcr.io/kzmake/osaifu/scala/app
      custom:
        buildCommand: ./build.sh
        dependencies:
          paths:
            - build.sbt
            - "**/*.proto"
            - "**/*.scala"
            - "**/*.sbt"
          ignore:
            - "**/target"
    - image: ghcr.io/kzmake/osaifu/scala/gateway
      context: ./gateway
      docker:
        dockerfile: ./gateway/Dockerfile
deploy:
  kustomize:
    paths:
      - manifest/overlays/localhost
portForward:
  - resourceType: service
    resourceName: app
    namespace: default
    port: 8080
    localPort: 8080
  - resourceType: service
    resourceName: app
    namespace: default
    port: 50051
    localPort: 50051
profiles:
  - name: localhost
