---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: osaifu
          image: ghcr.io/kzmake/osaifu/scala:latest
          envFrom:
            - secretRef:
                name: app-secret
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 32Mi
          ports:
            - name: grpc
              containerPort: 50051
          livenessProbe:
            tcpSocket: { port: 50051 }
            initialDelaySeconds: 10
          readinessProbe:
            tcpSocket: { port: 50051 }
            initialDelaySeconds: 5
            failureThreshold: 1
            periodSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name:  app
spec:
  type: ClusterIP
  selector:
    app:  app
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
---
apiVersion: v1
kind: Secret
metadata:
  name:  app-secret
stringData:
